### ISSUE TITLE
Cant build the app with current etmf workaround!

### ISSUE THREAD

**Issue by OnlinePage** [toonvanvr/electron-transparency-mouse-fix#19]
HI @toonvanvr  as discussed earlier (thanks for quick replies), the solution works , but now in order to build the app specific for platforms(windows) using `electron-builder` , this throws errors as in the image.
![etmf_issue](https://user-images.githubusercontent.com/61045650/208984670-6d111768-28b6-43cd-b919-694b11e72518.png)

From above what I get is the issue is because of `electron-transparency-mouse-fix` is not formally under `nodemodules` and is in the public directory and imported manually.

Can guide upon this as of now?

**Comment by OnlinePage** [comment]
Olay so fixed it by manually putting require dependencies of `etmf` to the project level `package.json`and then build!

**Comment by toonvanvr** [comment]
I would've suggested that too, but it should not be required indeed. I'll look at it next year, too busy now.
