### ISSUE TITLE
click-through not possible before click-on hovered

### ISSUE THREAD

**Issue by rgk85** [toonvanvr/electron-transparency-mouse-fix#2]
Hi,

I implemented the script and it works great, except for 1 thing.
It doesn't seem like the click-through is possible before you have hovered a click-on, initially i thought it was my implementation of the script but after running the demo i'm facing the same issue.

Is there a way around this so that click-through is upon startup actually click-through ?

In this image i havn't had my mouse over anything yet but the click-through, yet i'm not able to select the underlying text
![image](https://user-images.githubusercontent.com/40987871/53739064-2563fa80-3e91-11e9-9c0b-1a76eb225b03.png)

After mouse over on the click-on element i can select the underlying text under the click-through area.
![image](https://user-images.githubusercontent.com/40987871/53739137-53493f00-3e91-11e9-8586-d82ea79f3036.png)

**Comment by toonvanvr** [comment]
I'm working on a project that uses this library again, so I'll revisit the code one of these days and try to find the bug. Thanks for the clear explanation.

If you're eager to fix it before that time, the built in log option may help you figuring out when setIgnoreMouseEvents gets triggered.

**Comment by toonvanvr** [comment]
I'm revisiting this issue now I've got access to macOS. Didn't forget you! 😎

**Comment by toonvanvr** [comment]
The initial pointer position can be retrieved from an onload event. Will be fixed in v2.

**Comment by toonvanvr** [comment]
Fixed in v2 which is too early to release right now.

33747845afc0fe4a9164392e397fa58f546d5ef1

**Comment by Jip-Hop** [comment]
Is this fix included in the current release on npm, 1.0.0-rc.1?

**Comment by shash7** [comment]
bump

**Comment by toonvanvr** [comment]
I didn't realize this lib was still in use until I checked npm. Not sure if I'll have the time to verify everything works. Bump again if I don't respond after this weekend.

**Comment by toonvanvr** [comment]
I'm working on making the library bugfree cross-platform with focus on macOS (as I may be using this for a hobby project) and Windows. My personal laptop currently runs Ubuntu 20.04 Budgie & Gnome, so they may be supported after a while too. Linux transparency/clickthrough bugs have been very irregular over the last years though, so don't count on them being supported in the end. I'm diving pretty deep into the Electron differences across platforms right now, so a v2 release may land by the end of next weekend as alpha.

**Comment by llaver** [comment]
Hi @toonvanvr did v2 ever get any closer to release? I'm using this for a slow long term hobby project as well.

**Comment by toonvanvr** [comment]
@llaver
I have picked up the code several times but quit the day after because I didn't really have a useful project to test it with. Kind of lacking motivation. Is your project open source? I'd love to see what people do with it. It may get me working on it again.
