### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by Manwe-777** [toonvanvr/electron-transparency-mouse-fix#5]
> Unhandled Error
> TypeError: Cannot read property 'classList' of null
>     at TransparencyMouseFix.altCheckHover (../electron-transparency-mouse-fix.js:250:16)
>     at TransparencyMouseFix._scopedAltCheckHover (../electron-transparency-mouse-fix.js:69:44)

So, I implemented the script in my project (that makes a lot of use of transparency, hover and click-trough to create an overlay on the screen) and upon loading the elements the script kept crashing with that error.

https://github.com/toonvanvr/electron-transparency-mouse-fix/blob/67b6cd48991ecb78dbc0d5a3fde70bd5441e1025/src/electron-transparency-mouse-fix.js#L250

Simply adding a null check ( `if (tgt && ..)` ) seems to work flawlessly.

**Comment by toonvanvr** [comment]
Hi Manuel,  thanks for noticing. I'll try checking it out tomorrow.

**Comment by toonvanvr** [comment]
Fixed in c1502f761570407c75b1b881dd632134dc7a8dd2
