### ISSUE TITLE
Window blocks all mouse interactions unless I hover over the visible element.

### ISSUE THREAD

**Issue by shash7** [toonvanvr/electron-transparency-mouse-fix#8]
It seems like this library has a issue with setting some initial value. By default, clicks and other events don't go through unless I hover over the visible elements(i.e, the ones which have pointer events on)

I dug through the code but couldn't find any setting to set the initial behaviour.

Has anyone got any idea why is this happening?

**Comment by shash7** [comment]
It seems like setting this._ignoringMouse to true fixes this.
Btw this happens on Windows, not sure about Mac and Linux.

**Comment by toonvanvr** [comment]
I'm working on a v2 and am trying to incorporate all fixes. Thanks for logging the issue.
